# Generated by Django 5.0.4 on 2024-04-27 16:02

import apps.lobby.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroNovedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.CharField(max_length=30, verbose_name='')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hours', models.TimeField(verbose_name='Hora')),
                ('desc', models.TextField(blank='False', verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Libros de Eventos',
                'verbose_name_plural': 'Libros de Eventos',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminacion')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('nac', models.CharField(blank=True, choices=[('VE', 'VENEZOLANO'), ('EX', 'EXTRANJERO')], max_length=2, null=True, verbose_name='Nacionalidad')),
                ('dni', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Cedula')),
                ('first_name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=40, verbose_name='Apellido')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True, verbose_name='Género')),
                ('photo', models.ImageField(default='photo/default.jpg', upload_to=apps.lobby.models.visitor_photo_upload_path, verbose_name='Fotografía')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
                'ordering': ['dni'],
                'permissions': (('permiso_personalizado', 'Describe el permiso'),),
            },
        ),
        migrations.CreateModel(
            name='AccessSEDE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.DateField(verbose_name='Fecha del Dia')),
                ('hours', models.TimeField(verbose_name='Hora de Entrada')),
                ('hoursEx', models.TimeField(blank=True, null=True, verbose_name='Hora de Salida')),
                ('departaments', models.CharField(blank=True, choices=[('TALENTO HUMANO', 'TALENTO HUMANO'), ('TECNOLOGIA', 'TECNOLOGIA'), ('ADMINISTRACION', 'ADMINISTRACION'), ('CONSULTORIA JURIDICA', 'CONSULTORIA JURIDICA'), ('SERVICIOS GENERALES', 'SERVICIOS GENERALES'), ('COMERCIALIZACION', 'COMERCIALIZACION'), ('CENTRO DE ESTUDIO DEL AGUA', 'CENTRO DE ESTUDIO DEL AGUA'), ('VP. GESTION INTERNA', 'VP. GESTION INTERNA'), ('VP. GESTION COMERCIAL', 'VP. GESTION COMERCIAL'), ('PRESIDENCIA', 'PRESIDENCIA')], max_length=30, null=True, verbose_name='Oficina a Visitar')),
                ('obs', models.TextField(blank=True, default='SIN OBSERVACIONES', max_length=140, null=True, verbose_name='Observaciones')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='lobby.person')),
            ],
            options={
                'verbose_name': 'Listado Accesos',
                'verbose_name_plural': 'Listado Accesos',
                'ordering': ['entry', 'hours'],
            },
        ),
    ]
